"""
model1.py

Public entry point for the Functional Consistency Model (M1).
This is the only file the rest of the system needs to import.

Usage:
    from model1 import score_profile

    result = score_profile(profile_dict)
    print(result["functional_risk_score"])   # 0.0 → clean, 1.0 → fraud
    print(result["risk_level"])              # "low" / "medium" / "high" / "critical"
    print(result["flags"])                   # which pairs triggered
    print(result["pair_scores"])             # individual scores for explainability
"""

import time

from dataset_generation.model1.feature_extractor import extract_m1_features
from dataset_generation.model1.scorer import compute_functional_risk_score_detailed


def score_profile(profile: dict, include_profiling: bool = False) -> dict:
    """
    Score a single profile for functional consistency.

    Args:
        profile: raw profile dict (as generated by legitimate_generator.py
                 or loaded from profiles.csv)

    Returns:
        {
            "profile_id":             str,
            "functional_risk_score":  float,   # 0=clean, 1=fraud
            "risk_level":             str,      # low / medium / high / critical
            "pair_scores":            dict,     # per-pair breakdown
            "flags":                  list,     # pairs that crossed threshold
            "features_used":          dict,     # extracted features (for debugging)
        }
    """
    extract_started = time.perf_counter()
    features = extract_m1_features(profile)
    extraction_ms = (time.perf_counter() - extract_started) * 1000

    score_started = time.perf_counter()
    scored = compute_functional_risk_score_detailed(features, collect_profiling=include_profiling)
    scoring_ms = (time.perf_counter() - score_started) * 1000

    output = {
        "profile_id":            profile.get("profile_id", "unknown"),
        "functional_risk_score": scored["functional_risk_score"],
        "risk_level":            scored["risk_level"],
        "pair_scores":           scored["pair_scores"],
        "flags":                 scored["flags"],
        "features_used":         features,
        "rule_results":          scored["rule_results"],
        "top_contributors":      scored["top_contributors"],
        "score_breakdown":       scored["score_breakdown"],
        "uncertainty_summary":   scored["uncertainty_summary"],
    }
    if include_profiling:
        output["profiling"] = {
            "extraction_ms": extraction_ms,
            "scoring_ms": scoring_ms,
            "rule_runtimes_ms": scored.get("profiling", {}).get("rule_runtimes_ms", {}),
        }
    return output


def score_profiles_batch(profiles: list) -> list:
    """
    Score a list of profiles. Returns a list of result dicts.
    Use this when processing the full dataset.
    """
    return [score_profile(p) for p in profiles]
