"""
model1.py

Public entry point for the Functional Consistency Model (M1).
This is the only file the rest of the system needs to import.

Usage:
    from model1 import score_profile

    result = score_profile(profile_dict)
    print(result["functional_risk_score"])   # 0.0 → clean, 1.0 → fraud
    print(result["risk_level"])              # "low" / "medium" / "high" / "critical"
    print(result["flags"])                   # which pairs triggered
    print(result["pair_scores"])             # individual scores for explainability
"""

from feature_extractor import extract_m1_features
from scorer import compute_functional_risk_score


def score_profile(profile: dict) -> dict:
    """
    Score a single profile for functional consistency.

    Args:
        profile: raw profile dict (as generated by legitimate_generator.py
                 or loaded from profiles.csv)

    Returns:
        {
            "profile_id":             str,
            "functional_risk_score":  float,   # 0=clean, 1=fraud
            "risk_level":             str,      # low / medium / high / critical
            "pair_scores":            dict,     # per-pair breakdown
            "flags":                  list,     # pairs that crossed threshold
            "features_used":          dict,     # extracted features (for debugging)
        }
    """
    features = extract_m1_features(profile)

    functional_risk_score, pair_scores, flags, risk_level = \
        compute_functional_risk_score(features)

    return {
        "profile_id":            profile.get("profile_id", "unknown"),
        "functional_risk_score": functional_risk_score,
        "risk_level":            risk_level,
        "pair_scores":           {k: round(v, 4) for k, v in pair_scores.items()},
        "flags":                 flags,
        "features_used":         features,
    }


def score_profiles_batch(profiles: list) -> list:
    """
    Score a list of profiles. Returns a list of result dicts.
    Use this when processing the full dataset.
    """
    return [score_profile(p) for p in profiles]
